/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./sections/**/*.{html,js,jsx,ts,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  mode: "jit",

  theme: {
    extend: {
      colors: {
        "primary-black": "#1A232E",
        "secondary-white": "#c7c7c7",
      },
      fontFamily: {
        roboto: "Roboto",
      },
      // animation: {
      //   slideup: "slideup 0.7s ease-in-out",
      //   slideup0: "slideup 0.5s ease-in-out",
      //   slideup42: "slideup42 1s ease-in-out",
      //   slideup422: "slideup42 0.6s ease-in-out",
      //   slideup423: "slideup42 1.4s ease-in-out",
      //   slidedown: "slidedown 1s ease-in-out",
      //   slidedown2: "slidedown2 1.8s ease-in-out",
      //   slidelefttranfrom: "slidelefttranfrom 1.5s ease-in-out",
      //   slideleft: "slideleft 1.2s ease-in-out",
      //   slideleftT2: "slideleft 1s ease-in-out",
      //   slideleftT3: "slideleft 1.3s ease-in-out",
      //   slideleftT4: "slideleft 1.6s ease-in-out",
      //   slideleft0: "slideleft 0.3s ease-in-out",
      //   slideleft3: "slideleft3 1s ease-in-out",
      //   slideleft4: "slideleft3 2.3s ease-in-out",
      //   slideleft2: "slideleft2 1.8s ease-in-out",
      //   slideright: "slideright 1s ease-in-out",
      //   slideright2: "slideright2 1.3s ease-in-out",
      //   slideright3: "slideright2 1.9s ease-in-out",
      //   widthChange: "widthChange 8s ease-in-out",
      //   dropdownHight: "dropdownHight 0.4s  ease",
      //   dropupHight: "dropupHight 1s ease-in-out",
      //   wave: "wave 1.2s linear infinite",
      //   slowfade: "slowfade 2.2s ease-in-out",
      //   slowfade2: "slowfade2 1.5s ease-in-out",
      //   slowfade3: "slowfade2 0.7s ease-in-out",
      //   shake: "shake 0.1s linear infinite",
      //   slowfadehidden: "slowfadehidden 2s ease-in-out",
      //   slowspin: "slowspin 0.2s linear infinite",
      //   Fastspin: "slowspin 2.5s linear infinite",
      //   flip: "flip 2s linear infinite",
      //   VerySlowspin: "slowspin 3.5s linear infinite",
      //   pluseCustom: "pluseCustom 1s linear infinite",
      // },
      transitionTimingFunction: {
        "out-flex": "cubic-bezier(0.05, 0.6, 0.4, 0.9)",
      },
    },
  },
  plugins: [],
};
